#! /bin/sh
#
# unity-conntester 
#
# Author:	Unity Technologies
#
# chkconfig:    2345 98 02
# description:  A (NAT) connectivity testing service for 
#               Unity game servers and clients.
# processname:  ConnTester
# pidfile:      /opt/unity-connection-tester/ConnTester.pid
# config:       /etc/monitrc
#
# ------------------------------------
# Change this to suit your setup

BINARYNAME=ConnTester
OPTIONS=""
USERNAME=""
HOMEDIR=/opt/unity-connection-tester

# config where you can define the UNITY_EXTERNAL_IP_x environment variables
if  [ -f /etc/sysconfig/unity-conntester ] ; then
	.  /etc/sysconfig/unity-conntester
fi

if [[ $UNITY_EXTERNAL_IP_1 ]]
then
	OPTIONS="-h $UNITY_EXTERNAL_IP_1"
fi

if [[ $UNITY_EXTERNAL_IP_2 && $UNITY_EXTERNAL_IP_3 && $UNITY_EXTERNAL_IP_4 ]]
then
	OPTIONS="$OPTIONS -b $UNITY_EXTERNAL_IP_2 $UNITY_EXTERNAL_IP_3 $UNITY_EXTERNAL_IP_3_ALIAS $UNITY_EXTERNAL_IP_4"
fi

COMMAND="./${BINARYNAME} -d $OPTIONS"

# ------------------------------------

RETVAL=0

# See how we were called.
case "$1" in
  start)
	[ -f ${HOMEDIR}/${BINARYNAME}.pid ] && echo $BINARYNAME already running && exit 0
	if [ ! -w /var/lock/subsys/ ]; then 
		echo "Please run as a super user"
		exit 0
	fi

	echo -n "Starting $BINARYNAME: "
	if [ -z ${USERNAME+x} ]
	then

	        su $USERNAME -c "cd ${HOMEDIR} && $(COMMAND)"
	else
		cd ${HOMEDIR} && $(COMMAND)
	fi
	RETVAL=$?
        echo
	[ $RETVAL = 0 ] && touch /var/lock/subsys/$BINARYNAME
	;;
  stop)
        echo -n "Stopping $BINARYNAME: "
	cat ${HOMEDIR}/${BINARYNAME}.pid | xargs kill
	RETVAL=$?
        echo
	[ $RETVAL = 0 ] && rm -f /var/lock/subsys/$BINARYNAME
        ;;
  restart)
  	$0 stop
	sleep 5
	$0 start
	RETVAL=$?
	;;
  condrestart)
       [ -e /var/lock/subsys/$BINARYNAME ] && $0 restart
       ;;
  status)
        [ -f ${HOMEDIR}/${BINARYNAME}.pid ] && echo $BINARYNAME is running || echo $BINARYNAME is not running
	RETVAL=$?
	;;
  *)
	echo "Usage: $0 {start|stop|restart|condrestart|status}"
	exit 1
esac

exit $RETVAL
